apiVersion: apps/v1
kind: Deployment
metadata:
  name: example1
  labels:
    hello: world
    env: base
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app
        image: httpd
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "256m"
